language: go

go:
  - '1.14.x'

services:
  - docker

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
    - GOARCH=amd64

before_script:
  # Download and install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

  # Download and install KinD
  - curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64" && chmod +x ./kind && sudo mv ./kind /usr/local/bin/
  
  # Create a new Kubernetes cluster using KinD
  - kind create cluster

  # Set KUBECONFIG environment variable
  - export KUBECONFIG="$(kind get kubeconfig-path)"

script:
  - make check-fmt
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)